spring:
  datasource:
    url: jdbc:mysql://localhost:3307/feedsystem?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: your_mysql_username
    password: your_mysql_password
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: your_redis_password
  rabbitmq:
    host: localhost
    port: 5672
    username: your_rabbitmq_username
    password: your_rabbitmq_password

jwt:
  secret: your_jwt_secret
  access-token-expire-days: 1
  refresh-token-expire-days: 7
